export const products = [
  {
    id: 1,
    image: "iPhone13-pro.png",
    name: "iPhone 13 Pro",
    price: "K999.00",
    description: "Latest iPhone 13 pro",
    category: "phone",
    slug: "iphone-13-pro-max",
    popular: true,
    featured: false,
  },
  {
    id: 2,
    image: "iPhone14.png",
    name: "iPhone 14",
    price: "K899.00",
    description: "Latest iPhone 14",
    category: "phone",
    slug: "iphone-14-max",
    popular: false,
    featured: true,
  },
  {
    id: 3,
    image: "iPhone14-pro.png",
    name: "iPhone 14 Pro",
    price: "K1299.00",
    description: "Latest iPhone 14 pro",
    category: "phone",
    slug: "iphone-14-pro-max",
    popular: true,
    featured: false,
  },
  {
    id: 4,
    image: "iPhone13-pro.png",
    name: "iPhone 13 Pro",
    price: "K999.00",
    description: "Latest iPhone 13 pro",
    category: "phone",
    slug: "iphone-13-pro",
    popular: false,
    featured: true,
  },
  {
    id: 5,
    image: "iPhone14.png",
    name: "iPhone 14",
    price: "K899.00",
    description: "Latest iPhone 14",
    category: "phone",
    slug: "iphone-14",
    popular: false,
    featured: true,
  },
  {
    id: 6,
    image: "iPhone14-pro.png",
    name: "iPhone 14 Pro",
    price: "K1299.00",
    description: "Latest iPhone 14 pro",
    category: "phone",
    slug: "iphone-14-pro",
    popular: false,
    featured: true,
  },
  {
    id: 7,
    image: "item1.png",
    name: "Smart Watch",
    price: "K299.00",
    description: "Latest Smart Watch",
    category: "watch",
    slug: "smart-watch",
    popular: true,
    featured: false,
  },
  {
    id: 8,
    image: "item2.png",
    name: "Apple Smart Watch",
    price: "K299.00",
    description: "Latest Apple Smart Watch",
    category: "watch",
    slug: "apple-smart-watch",
    popular: true,
    featured: false,
  },
  {
    id: 9,
    image: "jbl1.png",
    name: "Bluetooth Speaker",
    price: "K599.00",
    description: "Latest Bluetooth Speaker",
    category: "accessories",
    slug: "jbl-speaker1",
    popular: false,
    featured: true,
  },
  {
    id: 10,
    image: "jbl2.png",
    name: "JBL Speaker",
    price: "K699.00",
    description: "Latest JBL Speaker",
    category: "accessories",
    slug: "jbl-speaker2",
    popular: false,
    featured: true,
  },
  {
    id: 11,
    image: "hphone1.png",
    name: "Headphone",
    price: "K199.00",
    description: "Latest Headphone",
    category: "accessories",
    slug: "jbl-headphone1",
    popular: true,
    featured: false,
  },
  {
    id: 12,
    image: "hphone2.png",
    name: "Headphone",
    price: "K199.00",
    description: "Latest Headphone",
    category: "accessories",
    slug: "jbl-headphone2",
    popular: true,
    featured: false,
  },
  {
    id: 13,
    image: "3in1Charger.png",
    name: "3in1 Charger",
    price: "K99.00",
    description: "Latest 3in1 Charger",
    category: "accessories",
    slug: "3in1-charger",
    popular: false,
    featured: false,
  },
  {
    id: 14,
    image: "car_charger.png",
    name: "Car Charger",
    price: "K49.00",
    description: "Latest Car Charger",
    category: "accessories",
    slug: "car-charger",
    popular: false,
    featured: false,
  },
  {
    id: 15,
    image: "cherger.png",
    name: "Charger",
    price: "K49.00",
    description: "Latest Charger",
    category: "accessories",
    slug: "charger",
    popular: false,
    featured: false,
  },
  {
    id: 16,
    image: "earpod.png",
    name: "Earpod",
    price: "K129.00",
    description: "Latest Earpod",
    category: "accessories",
    slug: "earpod",
    popular: false,
    featured: false,
  },
  {
    id: 17,
    image: "hset.png",
    name: "Headset",
    price: "K69.00",
    description: "Latest Headset",
    category: "accessories",
    slug: "headset",
    popular: false,
    featured: false,
  },
  {
    id: 18,
    image: "wireless_hset.png",
    name: "Wireless Headset",
    price: "K119.00",
    description: "Latest Wireless Headset",
    category: "accessories",
    slug: "wireless-headset",
    popular: false,
    featured: false,
  },
  {
    id: 19,
    image: "keyboard_led.png",
    name: "Keyboard",
    price: "K159.00",
    description: "LED Keyboard",
    category: "accessories",
    slug: "led-keyboard",
    popular: false,
    featured: false,
  },
  {
    id: 20,
    image: "keyboard_mouse.png",
    name: "Keyboard Plus Mouse",
    price: "K189.00",
    description: "Latest Keyboard Plus Mouse",
    category: "accessories",
    slug: "keyboard-mouse",
    popular: false,
    featured: false,
  },
  {
    id: 21,
    image: "mouse.png",
    name: " Mouse",
    price: "K39.00",
    description: "Latest Mouse",
    category: "accessories",
    slug: "mouse",
    popular: false,
    featured: false,
  },
  {
    id: 22,
    image: "mem_card.png",
    name: "Sandisk Memory Card",
    price: "K69.00",
    description: "Latest Sandisk Memory Card",
    category: "accessories",
    slug: "sandisk-memory-card",
    popular: false,
    featured: false,
  },
  {
    id: 23,
    image: "sandisk_usb.png",
    name: "Sandisk USB",
    price: "K69.00",
    description: "Latest Sandisk USB",
    category: "accessories",
    slug: "sandisk-usb",
    popular: false,
    featured: false,
  },
  {
    id: 24,
    image: "sony_usb.png",
    name: "Sony USB",
    price: "K69.00",
    description: "Latest Sony USB",
    category: "accessories",
    slug: "sony-usb",
    popular: false,
    featured: false,
  },
  {
    id: 25,
    image: "usb_asoted.png",
    name: "Assorted USB",
    price: "K69.00",
    description: "Latest Assorted USB",
    category: "accessories",
    slug: "assorted-usb",
    popular: false,
    featured: false,
  },
];
